# -*- coding: utf-8 -*-
"""Texto de cada ficha del manual de ejercicios del bloque R1."""

# slug, titulo, para_que, pasos, error, aviso (opcional, sale en rojo)
FICHAS = {

"02": ("Movilidad y activación", "El bloque que abre todos los días. Cuesta 20 minutos y es lo que más rinde en R1.", [

("90-90-cadera", "90/90 de cadera",
 "Devuelve rotación a la cadera para que la ingle no tenga que absorber el giro que la cadera no hace.",
 ["Siéntate en el suelo con la pierna de delante doblada a 90 grados y la de detrás también a 90, hacia el lado.",
  "Espalda larga, pecho alto. Apoya las manos al lado para no hundirte.",
  "Aguanta dos minutos por lado respirando tranquilo, o cambia de lado despacio si prefieres moverte."],
 "Redondear la espalda y compensar con el tronco en vez de abrir la cadera.",
 "Si notas pinchazo en la ingle al abrir, reduce el rango hasta que solo sea tirantez."),

("adductor-rockback", "Adductor rockback",
 "Mueve el aductor en un rango cómodo sin estirarlo de forma agresiva, que es lo que lo irrita.",
 ["A cuatro patas, estira una pierna hacia el lado con el pie apoyado en el suelo.",
  "Manos bajo los hombros, espalda plana como una mesa.",
  "Lleva el culo hacia atrás despacio y vuelve. Dos series de diez por lado."],
 "Ir demasiado atrás buscando el estiramiento máximo.",
 "Esto no es un estiramiento a fondo. Debe notarse suave, nunca al límite."),

("movilidad-cadera-pie", "Movilidad activa de cadera de pie",
 "Prepara la cadera para el resto de la sesión con movimiento activo, no con estiramiento pasivo.",
 ["De pie, sujétate a algo firme con una mano.",
  "Cruza la pierna por delante del cuerpo y vuelve a abrirla, en un arco controlado.",
  "Dos minutos alternando, sin coger inercia."],
 "Lanzar la pierna con impulso y rebotar al final del recorrido.",
 None),

("brace-respiracion", "Brace con respiración 360°",
 "Enseña al abdomen a ponerse firme sin bloquear la respiración. Es la base para que el core proteja el pubis.",
 ["Boca arriba, rodillas dobladas, manos en las costillas laterales.",
  "Inhala por la nariz notando cómo las costillas se abren hacia los lados, no solo hacia arriba.",
  "Exhala y tensa el abdomen como si fueran a darte un toque suave. Aguanta 5-8 segundos sin dejar de respirar."],
 "Aguantar el aire o arquear la zona lumbar.",
 None),

("isometrico-aductor", "Aducción isométrica con balón",
 "El ejercicio central de todo el bloque R1. Carga el aductor sin movimiento, que es la forma de recuperar tolerancia y de bajar el dolor.",
 ["Boca arriba, rodillas dobladas, un balón o cojín firme entre las rodillas.",
  "Aprieta al porcentaje que toque ese día: 50 % en los días 1-3, 60 % en los 4-7, 70 % en los 8-11 y 80 % en los 12-14.",
  "Mantén 30-45 segundos y descansa otros 30. Cinco series."],
 "Apretar a tope el primer día porque no duele en el momento.",
 "Se tolera hasta 3/10 durante la serie, pero no debe subir dentro de la serie. Si la serie 4 duele más que la 1, se corta ahí."),

("puente-gluteo", "Puente de glúteo",
 "Pone al glúteo a hacer su trabajo. Cuando el glúteo no empuja, el aductor compensa y se sobrecarga.",
 ["Boca arriba, pies planos a la anchura de la cadera, brazos al lado.",
  "Aprieta los glúteos y sube la cadera hasta alinear hombros, cadera y rodillas.",
  "Aguanta dos segundos arriba y baja controlando. Dos series de quince."],
 "Pasarse de subida arqueando la lumbar, o empujar con los talones en lugar de apretar el glúteo.",
 None),

("pallof-press", "Pallof press",
 "Entrena al tronco a no girarse cuando algo tira de él. Es el gesto que protege el pubis al chutar y al cambiar de dirección.",
 ["De lado a una polea o goma sujeta a la altura del pecho, sujeta el agarre con las dos manos junto al esternón.",
  "Estira los brazos al frente sin dejar que el tronco gire ni un grado.",
  "Vuelve lento. Dos series de diez por lado."],
 "Dejar que el cuerpo rote o balancearse para ayudarse.",
 None),

("dead-bug", "Dead bug",
 "Coordina abdomen y piernas sin tirar de la ingle. Es el paso previo a cualquier core más exigente.",
 ["Boca arriba, brazos al techo, rodillas a 90 grados sobre la cadera.",
  "Baja un brazo por encima de la cabeza y la pierna contraria estirada, despacio, como un robot lento.",
  "Vuelve al centro y cambia de lado. Dos series de ocho por lado."],
 "Arquear la espalda al extender la pierna, o ir rápido.",
 "La lumbar no se despega del suelo. Si se despega, baja menos la pierna."),

]),

"03": ("Gimnasio", "Cuatro sesiones por semana. En R1 el tren superior lleva el peso del trabajo y la pierna entra solo por donde no molesta.", [

("press-pecho-maquina", "Press de pecho en máquina",
 "Pectoral y tríceps con la espalda apoyada, que es lo que la hace segura ahora: no hay que estabilizar con el tronco.",
 ["Siéntate con la espalda pegada al respaldo y los pies planos en el suelo.",
  "Agarra las empuñaduras a la altura media del pecho, codos a unos 45 grados del cuerpo.",
  "Empuja hasta casi estirar y vuelve controlando. Tres series de diez, dejando tres repeticiones en reserva."],
 "Sacar los hombros hacia delante al empujar y despegar la espalda del respaldo.",
 None),

("press-inclinado-mancuernas", "Press inclinado con mancuernas",
 "Parte alta del pectoral y hombro. Con mancuernas cada lado trabaja por su cuenta y se corrigen descompensaciones.",
 ["Banco a unos 30 grados, mancuernas a la altura del pecho, pies planos.",
  "Empuja hacia arriba y ligeramente hacia dentro, sin chocar las mancuernas.",
  "Baja despacio hasta notar el pecho estirado. Tres series de diez."],
 "Subir el banco demasiado, que convierte el ejercicio en press de hombro.",
 None),

("press-militar-maquina", "Press militar en máquina",
 "Hombro completo con trayectoria guiada, sin tener que estabilizar de pie.",
 ["Siéntate con la espalda apoyada y los pies firmes.",
  "Empuja las empuñaduras hacia arriba con los codos debajo de las muñecas.",
  "Baja hasta que las manos queden a la altura de las orejas. Tres series de diez."],
 "Arquear la lumbar para sacar la última repetición.",
 None),

("elevaciones-laterales", "Elevaciones laterales",
 "Deltoides medio, que es el que da la forma del hombro. Poco peso y mucho control.",
 ["De pie, una mancuerna en cada mano, codos ligeramente doblados.",
  "Sube los brazos por los lados hasta la altura del hombro, no más.",
  "Baja despacio contando dos segundos. Tres series de doce a quince."],
 "Coger impulso con las piernas y la espalda para levantar más peso del que toca.",
 None),

("triceps-polea", "Extensión de tríceps en polea",
 "Tríceps con tensión constante y cero exigencia para el resto del cuerpo.",
 ["De frente a la polea alta, codos pegados al cuerpo, un pie ligeramente adelantado.",
  "Empuja la barra hacia abajo hasta estirar del todo los brazos.",
  "Sube controlando sin dejar que los codos se abran. Tres series de doce a quince."],
 "Despegar los codos del cuerpo y convertirlo en un empuje de pecho.",
 None),

("curl-femoral", "Curl femoral en máquina",
 "Isquiosurales. Es una de las dos únicas entradas de pierna en la primera semana porque no toca el aductor ni el flexor de cadera.",
 ["Tumbado boca abajo con la cadera pegada al banco y el rodillo sobre los tobillos.",
  "Lleva los talones hacia el glúteo apretando al final.",
  "Baja despacio sin dejar caer el peso. Tres series de doce."],
 "Levantar la cadera del banco para ayudarse.",
 "Si al flexionar notas tirón en la ingle, para y avísalo. No debería aparecer ahí."),

("extension-cuadriceps", "Extensión de cuádriceps",
 "Cuádriceps aislado, sentado y con la cadera fija. La otra entrada segura de pierna en la primera semana.",
 ["Siéntate con la espalda apoyada y el rodillo sobre la parte baja de la espinilla.",
  "Estira las piernas hasta casi bloquear la rodilla, apretando el muslo arriba.",
  "Baja controlando. Tres series de doce."],
 "Lanzar la pierna y dejarla caer de golpe.",
 None),

("jalon-al-pecho", "Jalón al pecho agarre amplio",
 "Dorsal y espalda alta. Abre el ejercicio de tirón y es el que más masa aporta arriba.",
 ["Siéntate con los muslos bajo los rodillos y agarra la barra ancho, palmas al frente.",
  "Tira la barra hacia la parte alta del pecho llevando los codos abajo y atrás.",
  "Sube controlando hasta estirar del todo. Tres series de diez."],
 "Echarse muy atrás y tirar con inercia de todo el cuerpo.",
 "Estabilizar apretando el abdomen bajo es la trampa de este ejercicio. Si notas que tira de la ingle, baja el peso."),

("remo-maquina-neutro", "Remo en máquina agarre neutro",
 "Espalda media con el pecho apoyado, que quita cualquier exigencia a la zona lumbar y al core.",
 ["Pecho contra el soporte, agarre neutro con las palmas mirándose.",
  "Tira hasta que los codos pasen las costillas juntando las escápulas.",
  "Vuelve estirando del todo. Tres series de diez."],
 "Separar el pecho del soporte para tirar más fuerte.",
 None),

("remo-mancuerna", "Remo con mancuerna a una mano",
 "Dorsal lado a lado, corrigiendo asimetrías.",
 ["Una rodilla y una mano en el banco, el otro pie en el suelo, espalda plana y paralela al suelo.",
  "Sube la mancuerna hacia la cadera pegando el codo al cuerpo.",
  "Baja estirando el brazo del todo. Tres series de diez por lado."],
 "Girar el tronco para subir más peso.",
 "Es el ejercicio del Plan B que más se cuela: al estabilizar aprietas el abdomen bajo. Si tira de la ingle, apóyate mejor y baja el peso."),

("face-pull", "Face pull en polea",
 "Hombro posterior y postura. Compensa todo el trabajo de empuje y protege el hombro.",
 ["Polea a la altura de la cara con cuerda, un paso atrás para tener tensión.",
  "Tira de la cuerda hacia la cara separando las manos, codos altos y abiertos.",
  "Termina con las manos junto a las orejas. Tres series de doce a quince."],
 "Bajar los codos y convertirlo en un remo.",
 None),

("curl-biceps-inclinado", "Curl de bíceps en banco inclinado",
 "Bíceps en posición estirada, que es donde más se construye.",
 ["Siéntate recostado en un banco a unos 60 grados, brazos colgando y ligeramente detrás del cuerpo.",
  "Sube la mancuerna sin mover el codo de su sitio.",
  "Baja despacio hasta estirar del todo. Tres series de diez."],
 "Adelantar el codo para ayudarse en la subida.",
 None),

("curl-martillo", "Curl martillo alterno",
 "Braquial y antebrazo. Da grosor al brazo y protege el codo.",
 ["De pie, mancuernas con las palmas mirándose, pulgares arriba.",
  "Sube una mancuerna hacia el hombro sin girar la muñeca.",
  "Baja controlando y alterna. Tres series de doce."],
 "Balancear el cuerpo hacia atrás en cada repetición.",
 None),

("gemelo-de-pie", "Gemelo de pie",
 "Gemelo y sóleo. Es la única pierna del martes y prepara el tobillo para cuando vuelva la carrera en R2.",
 ["Puntas de los pies en el borde de un escalón, talones al aire.",
  "Sube a la máxima punta apretando arriba un segundo.",
  "Baja despacio hasta notar el estiramiento. Tres series de quince."],
 "Rebotar abajo en lugar de controlar la bajada.",
 None),

]),

"04": ("Piscina y automasaje", "El agua descarga entre el 50 y el 90 % del peso del cuerpo. Es donde puedes moverte sin peaje.", [

("nado-espalda", "Nado espalda",
 "El único estilo recomendable ahora. Elonga el pecho y la cadera sin abrir la ingle.",
 ["Flota boca arriba con el cuerpo largo y horizontal.",
  "Brazada alterna por encima del hombro, sin prisa.",
  "Patada suave desde la cadera, sin abrir las piernas."],
 "Meter potencia y convertirlo en entrenamiento en lugar de recuperación.",
 "Braza y mariposa, no. La patada de braza abre y cierra la cadera justo por donde duele."),

("aqua-running", "Aqua running en agua profunda",
 "Sustituye a la carrera con impacto cero sobre la sínfisis del pubis. Es el mejor cardio del bloque R1.",
 ["Cinturón de flotación a la cintura, en la zona donde no haces pie.",
  "Corre en el sitio con la misma mecánica que en tierra, brazos incluidos.",
  "Diez minutos suaves: deberías poder hablar con normalidad."],
 "Inclinarse hacia delante y acabar nadando en vez de corriendo.",
 None),

("marching-agua", "Marching alto en agua",
 "Flexor de cadera y core con la resistencia del agua y sin impacto.",
 ["De pie con el agua por la cadera.",
  "Sube una rodilla hacia el pecho y baja controlando contra la resistencia del agua.",
  "Alterna durante cinco minutos, tronco erguido."],
 "Inclinar el tronco atrás para subir más la rodilla.",
 None),

("flotacion-pasiva", "Flotación pasiva",
 "Cierra la sesión de agua bajando el tono de todo. Cinco minutos que valen más de lo que parecen.",
 ["Boca arriba, brazos abiertos, sin hacer nada.",
  "Respira largo y suelta la mandíbula, los hombros y la cadera.",
  "Cinco minutos."],
 "Saltársela por parecer que no es entrenamiento.",
 None),

("pistola-cuadriceps", "Pistola en cuádriceps",
 "Descarga el muslo después del gimnasio. Cabezal de bola grande y presión media.",
 ["Sentado, apoya la pistola sobre el muslo sin clavar.",
  "Recorridos largos y lentos de rodilla hacia arriba.",
  "Uno o dos minutos por pierna."],
 "Buscar el punto que más duele y quedarse ahí clavando.",
 "Molestia de 0 a 3 sobre 10 durante. Al día siguiente igual o mejor, nunca peor."),

("pistola-aductor", "Pistola en aductor, solo mitad del muslo",
 "Suelta el cuerpo del aductor sin tocar la parte que está irritada.",
 ["Sentado con la pierna girada ligeramente hacia fuera.",
  "Trabaja solo la mitad del muslo, a media distancia entre rodilla y cadera.",
  "Recorridos cortos, un minuto por pierna."],
 "Subir hacia la ingle buscando el origen del dolor.",
 "Nunca los últimos 3-4 centímetros hacia el pubis, ni con pistola ni con presión fuerte. Ahí solo mano y suave."),

]),

"05": ("Fisioterapia y electroestimulación", "Con acceso ilimitado, el problema deja de ser tener poco y pasa a ser acumular demasiado sobre una zona ya sensible.", [

("ems-aductores", "Electrodos EMS en aductores",
 "Activa el aductor sin cargar la articulación. Complementa los isométricos, no los sustituye.",
 ["Cuatro electrodos sobre el vientre del músculo, en la cara interna del muslo.",
  "Programa de recuperación activa de 3 a 9 Hz, veinte minutos.",
  "Intensidad hasta ver contracción firme, sin dolor."],
 "Subir la intensidad buscando que duela.",
 "Nunca sobre pubis, ingle ni genitales. En días de parón, solo programas de recuperación, nunca de fuerza."),

("ems-gluteos", "Electrodos EMS en glúteos",
 "Refuerza el glúteo, que es el músculo que cierra la cadena y descarga al aductor.",
 ["Dos electrodos por glúteo, sobre la masa muscular.",
  "Recuperación activa veinte minutos, o fuerza resistencia solo en días sin gimnasio pesado.",
  "Dos o tres veces por semana."],
 "Encadenar sesión de fuerza con EMS de fuerza el mismo día sobre el mismo grupo.",
 None),

("fisio-gluteo-medio", "Trabajo manual en glúteo medio y TFL",
 "Es la zona que más descarga la ingle sin tocarla. Debería ser el grueso de tus sesiones de fisio.",
 ["Tumbado de lado en la camilla.",
  "El fisio trabaja el lateral de la cadera, por encima del hueso.",
  "Diez o quince minutos por lado."],
 "Pedir que se centre siempre en la ingle porque es donde duele.",
 "Máximo dos sesiones por semana con trabajo sobre la zona púbica. El resto, a lo que compensa."),

]),

"06": ("Cierre del día", "Diez minutos antes de dormir. El tejido se repara durmiendo, no entrenando.", [

("movilidad-nocturna", "Movilidad suave de cadera",
 "Baja el tono de la cadera antes de dormir y mejora la calidad del sueño.",
 ["Boca arriba, cruza un tobillo sobre la rodilla contraria formando un cuatro.",
  "Tira suave del muslo de apoyo hacia el pecho.",
  "Un minuto por lado, respirando largo."],
 "Forzar hasta el límite del estiramiento antes de dormir.",
 None),

("masaje-espalda-maquina", "Máquina de masaje de espalda",
 "Suelta la lumbar y la dorsal. Cuando la lumbar se suelta, el aductor deja de compensar.",
 ["Siéntate con el cojín de masaje contra la zona dorsal y lumbar.",
  "Intensidad media, entre cinco y diez minutos.",
  "Mejor después de entrenar que antes."],
 "Usarlo a máxima potencia pensando que cuanto más duele, mejor funciona.",
 "Nunca cerca de la ingle ni de la cara interna del muslo alto: el aparato no controla la presión."),

]),

"07": ("Nutrición", "Objetivo 137 g de proteína al día, repartidos. Vienes de un parón: no toca déficit.", [

("plato-modelo", "El plato modelo",
 "La referencia visual para no tener que pesar nada. Sirve para comida y para cena.",
 ["Un cuarto largo del plato de proteína: pollo, pescado, ternera magra, huevos o legumbres.",
  "Casi la mitad de carbohidrato: arroz integral, patata, quinoa o pasta integral.",
  "El resto verdura de colores, y un chorro de aceite de oliva virgen."],
 "Quedarse corto de carbohidrato pensando que así se recupera antes.",
 None),

("post-entreno", "Recarga post-entreno",
 "La ventana de después de entrenar es la más fácil de cumplir y la que más suma al total del día.",
 ["Entre treinta y sesenta minutos después de acabar.",
  "Leche, plátano y 25 g de proteína de suero. O yogur con fruta y miel.",
  "Y agua: entre medio litro y tres cuartos para recuperar."],
 "Saltárselo los días de sesión corta pensando que no cuenta.",
 None),

]),
}
