# -*- coding: utf-8 -*-
"""Core, recuperacion de aductor y pubis, estiramientos y gestos de futbol."""

V3 = {

"13": ("Core y abdominales",
       "En la pubalgia el abdominal no es estetica: el recto abdominal y el aductor tiran del "
       "mismo hueso en direcciones opuestas. Si el abdomen no sujeta la pelvis, el aductor "
       "trabaja de mas y la insercion se irrita.", [

("plancha-frontal", "Plancha frontal",
 "La base de todo. Enseña al abdomen a sostener la pelvis sin que la lumbar haga el trabajo.",
 ["Antebrazos en el suelo, codos justo debajo de los hombros.",
  "Cuerpo en línea recta de la cabeza a los talones, glúteo apretado.",
  "Aguanta 20 a 40 segundos respirando. Tres series."],
 "Dejar caer la cadera, que traslada toda la carga a la lumbar y al pubis.",
 "Si notas el pubis durante la plancha, acorta el tiempo hasta que no lo notes."),

("hollow-hold", "Hollow hold",
 "Trabaja el recto abdominal en tensión larga, que es exactamente lo que necesita para frenar la extensión del golpeo.",
 ["Boca arriba, lumbar pegada al suelo sin dejar hueco.",
  "Levanta hombros y piernas un palmo del suelo, cuerpo en forma de plátano suave.",
  "Aguanta 15 a 30 segundos. Tres series."],
 "Despegar la lumbar. En cuanto se despega, el ejercicio deja de servir y empieza a molestar.",
 "Empieza con las rodillas dobladas. Estirar las piernas multiplica la carga sobre el pubis."),

("dead-bug-banda", "Dead bug con banda",
 "La progresión del dead bug. La banda obliga a los brazos a sostener mientras las piernas se mueven.",
 ["Goma anclada detrás de la cabeza, brazos estirados hacia el techo sujetándola.",
  "Baja una pierna estirada muy despacio sin mover los brazos ni despegar la lumbar.",
  "Tres series de ocho por lado."],
 "Ir rápido. Este ejercicio solo funciona lento.",
 None),

("bicho-muerto-cruzado", "Dead bug isométrico con presión",
 "Versión sin movimiento, ideal cuando la zona está irritada: activa el abdomen profundo sin cargar el pubis.",
 ["Boca arriba, rodillas sobre la cadera a noventa grados.",
  "Empuja las manos contra las rodillas y las rodillas contra las manos, sin que nada se mueva.",
  "Aguanta diez segundos. Cinco repeticiones."],
 "Aguantar la respiración mientras empujas.",
 "Es el core más seguro que existe para ti. Úsalo los días de dolor 3."),

("plancha-hombro", "Plancha con toque de hombro",
 "Añade anti-rotación a la plancha. Es el gesto que protege al girar y al chutar.",
 ["Plancha alta sobre las manos, pies algo separados.",
  "Levanta una mano y toca el hombro contrario sin que la cadera se mueva un centímetro.",
  "Tres series de ocho por lado."],
 "Balancear la cadera al levantar la mano.",
 None),

("plancha-lateral-pie", "Plancha lateral con piernas estiradas",
 "La progresión de la plancha lateral corta. Exige mucho más al lateral de la pelvis.",
 ["De lado, antebrazo en el suelo, pies apilados uno sobre otro.",
  "Sube la cadera hasta la línea recta y levanta el brazo de arriba al techo.",
  "Veinte a cuarenta segundos por lado."],
 "Rotar el pecho hacia el suelo.",
 "Solo cuando la versión con rodillas salga limpia tres semanas seguidas."),

("pallof-rotacion", "Pallof de rodillas",
 "De rodillas se elimina la ayuda de las piernas y el trabajo cae entero sobre el core.",
 ["De rodillas sobre una colchoneta, de lado a la polea.",
  "Estira los brazos al frente sin dejar que el tronco gire.",
  "Tres series de diez por lado."],
 "Dejar que la cadera se abra hacia la polea.",
 None),

("rueda-abdominal", "Rueda abdominal de rodillas",
 "El ejercicio más exigente de anti-extensión. Prepara al abdomen para frenar el latigazo del golpeo.",
 ["De rodillas, rueda bajo los hombros, cadera ligeramente metida.",
  "Rueda hacia delante solo hasta la mitad del recorrido, con la espalda plana.",
  "Vuelve tirando con el abdomen. Tres series de seis."],
 "Ir demasiado lejos y arquear la lumbar, que en pubalgia es exactamente lo que no se debe hacer.",
 "No entra hasta R3. Es el que más carga la inserción del recto abdominal en el pubis."),

("elevacion-piernas", "Bajada de piernas controlada",
 "Trabaja el abdominal bajo, que es la zona que más floja suele estar en la pubalgia.",
 ["Boca arriba, manos bajo la lumbar o agarrado a un banco.",
  "Baja las dos piernas estiradas muy despacio y para a mitad de camino.",
  "Sube controlando. Tres series de ocho."],
 "Bajar hasta el suelo y despegar la lumbar en el último tramo.",
 "Si notas tirón en el pubis al bajar, dobla las rodillas y reduce el recorrido."),

("bird-dog", "Bird dog",
 "Coordina la pelvis con brazo y pierna contraria, que es el patrón de la carrera.",
 ["A cuatro patas, espalda plana como una mesa.",
  "Estira brazo y pierna contraria a la vez, sin que la cadera se incline.",
  "Aguanta dos segundos y cambia. Tres series de diez por lado."],
 "Subir la pierna más alto que la cadera, que arquea la lumbar.",
 None),

]),

"14": ("Aductor y pubis: recuperación",
       "El aductor se recupera cargándolo, no descansándolo. La clave está en el angulo y en la "
       "progresion: isometrico primero, luego movimiento, y siempre con el dia siguiente como juez.", [

("squeeze-45", "Squeeze a 45 grados",
 "El isométrico básico. A 45 grados de flexión de rodilla el aductor trabaja en su rango más cómodo.",
 ["Boca arriba, rodillas dobladas a unos 45 grados, pies planos.",
  "Balón o cojín firme entre las rodillas.",
  "Aprieta al porcentaje del día, aguanta 30 a 45 segundos, cinco series."],
 "Apretar a tope el primer día porque en el momento no duele.",
 "Es el ejercicio central de R1. Se tolera hasta 3 sobre 10 y no debe subir dentro de la serie."),

("squeeze-90", "Squeeze a 90 grados",
 "Mismo ejercicio con la cadera más flexionada. Trabaja otra porción del aductor y suele ser el ángulo que más molesta.",
 ["Boca arriba, caderas y rodillas a noventa grados, pies en el aire.",
  "Balón entre las rodillas, aprieta y mantén.",
  "Cinco series de 30 segundos."],
 "Empezar por este ángulo. Se introduce después del de 45.",
 "Si a 90 duele más que a 45, quédate en 45 una semana más. Esa diferencia es información."),

("squeeze-piernas-rectas", "Squeeze con piernas rectas",
 "El ángulo más exigente, con el aductor en posición larga. Es el último que entra y el que más se parece al gesto de chutar.",
 ["Boca arriba con las piernas estiradas.",
  "Balón entre los tobillos, aprieta sin levantar las piernas.",
  "Cinco series de 30 segundos."],
 "Meterlo antes de dominar los otros dos ángulos.",
 "No entra hasta el final de R2. Es el que más tensa la inserción."),

("aductor-maquina", "Aductor en máquina",
 "Fuerza concéntrica pura con carga graduable. Permite medir el progreso en kilos, que es lo que faltaba.",
 ["Sentado, espalda apoyada, muslos contra los soportes.",
  "Cierra las piernas de forma controlada y vuelve despacio.",
  "Tres series de doce a quince."],
 "Abrir demasiado al volver, que estira el aductor en carga.",
 "Prohibido en R1. Entra en R2 con rango corto y se amplía en R3."),

("deslizamiento-lateral", "Deslizamiento lateral con disco",
 "Trabaja el aductor frenando en el plano lateral, que es lo que hace al cambiar de dirección.",
 ["Un pie sobre un disco deslizante, el otro firme.",
  "Desliza la pierna hacia fuera despacio y tira para volver con el aductor.",
  "Tres series de ocho por lado."],
 "Abrir demasiado. El recorrido corto y controlado vale más que el amplio.",
 "Entra en R3, cuando el Copenhagen corto ya sale limpio."),

("puente-una-pierna", "Puente a una pierna",
 "Glúteo unilateral. Un glúteo fuerte estabiliza la pelvis y le quita trabajo al aductor.",
 ["Boca arriba, un pie plantado y la otra pierna estirada en el aire.",
  "Sube la cadera hasta la línea recta sin que la pelvis se incline.",
  "Tres series de diez por lado."],
 "Dejar caer el lado de la pierna que está en el aire.",
 None),

("marcha-puente", "Marcha en puente",
 "Enseña a mantener la pelvis nivelada mientras una pierna se mueve, que es lo que pasa al correr.",
 ["Desde la posición de puente con la cadera arriba.",
  "Sube una rodilla hacia el pecho sin que la cadera baje ni se incline.",
  "Tres series de ocho por lado."],
 "Perder altura de cadera en cada repetición.",
 None),

("adductor-rockback-banda", "Rockback con banda",
 "El rockback de siempre, con una banda que obliga al glúteo a participar.",
 ["A cuatro patas, banda ligera alrededor de los muslos, una pierna extendida al lado.",
  "Lleva la cadera atrás despacio y vuelve.",
  "Dos series de diez por lado."],
 "Usar una banda demasiado dura.",
 None),

]),

"15": ("Estiramientos para tu lesión",
       "Aviso que vale mas que los propios ejercicios: en la pubalgia el estiramiento agresivo del "
       "aductor EMPEORA el cuadro cuando la zona esta irritada. Lo que si hay que estirar es todo "
       "lo que tira de la pelvis desde arriba y desde atras: psoas, recto femoral, isquios, "
       "piramidal y cuadrado lumbar. El aductor se estira suave y el ultimo.", [

("estiramiento-psoas", "Estiramiento de psoas",
 "El psoas tira de la pelvis hacia delante y aumenta la tensión sobre el pubis. Es el estiramiento más importante para ti.",
 ["De rodillas sobre una colchoneta, una rodilla abajo y el otro pie delante.",
  "Mete la pelvis por debajo, como escondiendo el coxis, antes de avanzar.",
  "Aguanta 30 segundos por lado. Dos rondas."],
 "Arquear la lumbar y creer que estás estirando cuando solo estás pinzando la espalda.",
 "La pelvis metida es todo el ejercicio. Sin eso, no estiras el psoas."),

("estiramiento-recto-femoral", "Estiramiento de recto femoral",
 "El recto femoral cruza la cadera y tira del hueso ilíaco. Su tensión llega directa a la pelvis.",
 ["Igual que el de psoas, pero cogiendo el pie de atrás con la mano.",
  "Pelvis metida y rodilla apuntando al suelo.",
  "Treinta segundos por lado."],
 "Dejar que la rodilla se abra hacia fuera.",
 None),

("estiramiento-isquios", "Estiramiento de isquios",
 "Unos isquios cortos bascular la pelvis hacia atrás y descolocan todo el equilibrio del pubis.",
 ["Talón sobre un banco bajo, pierna estirada.",
  "Inclínate desde la cadera con la espalda recta, no doblando la espalda.",
  "Treinta segundos por lado."],
 "Redondear la espalda para llegar más lejos.",
 None),

("estiramiento-piramidal", "Estiramiento de piramidal",
 "El piramidal rota la cadera y, cuando está tenso, obliga al aductor a compensar en cada giro.",
 ["Boca arriba, cruza un tobillo sobre la rodilla contraria formando un cuatro.",
  "Tira del muslo de apoyo hacia el pecho con las dos manos.",
  "Treinta segundos por lado."],
 "Tirar de golpe. Debe entrar poco a poco.",
 None),

("estiramiento-cuadrado-lumbar", "Estiramiento de cuadrado lumbar",
 "Une la pelvis con las costillas. Si está tenso de un lado, la pelvis queda torcida y el pubis lo paga.",
 ["De pie, un brazo arriba y por encima de la cabeza.",
  "Inclínate hacia el lado contrario sin girar el tronco.",
  "Treinta segundos por lado."],
 "Girar el pecho al inclinarte, que convierte el estiramiento en otra cosa.",
 None),

("estiramiento-aductor-suave", "Estiramiento suave de aductor",
 "El único estiramiento de aductor que entra, y entra tarde. Mariposa sentado, sin forzar.",
 ["Sentado, plantas de los pies juntas y rodillas relajadas hacia los lados.",
  "Manos en los tobillos, espalda alta. No empujes las rodillas hacia abajo.",
  "Treinta segundos, dos rondas."],
 "Empujar las rodillas al suelo con las manos o con los codos.",
 "No se hace mientras el dolor esté por encima de 2. Con la inserción irritada, estirar es echar gasolina."),

("estiramiento-gato-camello", "Gato y camello",
 "Moviliza la pelvis y la lumbar sin cargar nada. Es el mejor primer movimiento del día.",
 ["A cuatro patas, arquea la espalda hacia el techo metiendo la cabeza.",
  "Luego deja caer el abdomen y sube la mirada, despacio.",
  "Diez ciclos lentos."],
 "Hacerlo rápido y sin llegar a los extremos del recorrido.",
 None),

("respiracion-90-90", "Respiración 90/90",
 "Baja el tono del psoas y de la pared abdominal. Es lo que cierra bien una sesión dura.",
 ["Boca arriba con las piernas apoyadas en un banco, caderas y rodillas a noventa grados.",
  "Manos en las costillas, inhala cuatro segundos y exhala seis.",
  "Cinco minutos."],
 "Respirar solo con el pecho.",
 None),

]),

"16": ("Fútbol: los gestos",
       "El orden importa mas que el volumen. Primero recibir y pasar, luego conducir, luego golpear "
       "en movimiento y, al final del todo, el balon parado, que es tu especialidad y el gesto que "
       "mas carga la insercion del recto abdominal en el pubis.", [

("control-orientado", "Control orientado",
 "El primer gesto que vuelve. No carga la pelvis y recupera la sensación de balón.",
 ["Recibe con el interior y desvía el balón hacia donde quieres ir en el mismo toque.",
  "Abre el cuerpo antes de que llegue la pelota.",
  "Diez minutos, con las dos piernas."],
 "Parar el balón y luego moverlo, que son dos toques en vez de uno.",
 None),

("pase-interior", "Pase con el interior",
 "El golpeo más seguro que existe para ti: poco recorrido, poca velocidad y cadera casi neutra.",
 ["Pie de apoyo al lado del balón, apuntando al destino.",
  "Tobillo bloqueado, golpea con la cara interna del pie.",
  "Acompaña bajo, sin levantar el balón."],
 "Golpear con la punta o con la cadera abierta de más.",
 "Es el primer golpeo que entra, en R3. Empieza a media distancia."),

("conduccion-conos", "Conducción entre conos",
 "Devuelve el control del balón en carrera sin exigir cambios de dirección agresivos.",
 ["Conos separados y línea amplia al principio.",
  "Balón cerca del pie, toques cortos.",
  "Cierra los conos solo cuando no notes nada al día siguiente."],
 "Meter cambios bruscos antes de tiempo.",
 None),

("pase-largo", "Pase largo",
 "Ya es un golpeo de verdad: carrera previa, extensión de cadera y latigazo. Aquí empieza el riesgo.",
 ["Carrera corta de dos o tres pasos, ligeramente en diagonal.",
  "Pie de apoyo firme al lado del balón, golpea con el empeine bajo.",
  "Acompaña el gesto sin frenarlo en seco."],
 "Frenar el gesto a mitad, que es cuando el abdominal recibe el tirón entero.",
 "Entra al final de R3, en series de diez a doce y solo a media potencia."),

("centro-banda", "Centro desde banda",
 "Combina carrera, golpeo y rotación de tronco. Es más exigente que el pase largo.",
 ["Carrera lateral, cuerpo ligeramente inclinado atrás.",
  "Envuelve el balón con el interior del empeine.",
  "Series de seis a ocho, no más."],
 "Buscar la máxima altura desde el primer centro.",
 "Entra en R4. Cuenta dentro del techo de golpeos del día."),

("golpeo-empeine", "Golpeo con empeine",
 "El disparo. Máxima velocidad de la cadera y máxima frenada del abdominal: el gesto que define tu recuperación.",
 ["Carrera de dos o tres pasos, último apoyo firme al lado del balón.",
  "Cadera al frente, pierna extendida a través del balón.",
  "Acompaña completo, sin cortar el movimiento."],
 "Chutar en frío o al final de la sesión, cuando el abdominal ya está cansado.",
 "Progresión estricta: 40 % en R3, 70-80 % en R4 y libre en R5. Nunca se salta un escalón."),

("falta-balon-parado", "Falta con balón parado",
 "Tu especialidad, y el gesto de más riesgo del proceso. Balón quieto y cero amortiguación: todo lo absorbe la pelvis.",
 ["Carrera curva de tres o cuatro pasos.",
  "Apoyo firme al lado del balón y golpeo envolvente con el interior del empeine.",
  "Series de seis a ocho, con un minuto de pausa y chequeo entre serie y serie."],
 "Encadenar veinte faltas seguidas porque van entrando. El daño de las faltas es acumulativo y aparece al día siguiente.",
 "No entra hasta el día 8 de R4. Techo de dieciséis golpeos parados por sesión en R4 y doce faltas en R5."),

("remate-cabeza", "Remate de cabeza",
 "Salto, giro de tronco y caída. Carga la pared abdominal más de lo que parece.",
 ["Salta con un pie y lleva el cuerpo en arco.",
  "Golpea con la frente, cuello firme, ojos abiertos.",
  "Series cortas, con caída controlada."],
 "Caer de espaldas o con el tronco arqueado.",
 "Entra en R4. El arqueo del salto tensa justo la inserción que te duele."),

]),
}
