# -*- coding: utf-8 -*-
"""Modelo de datos del plan de reinicio R1-R5 para la app movil."""

BLOQUES = [
    dict(id="R1", nombre="Descarga y control", desde="2026-08-17", dias=14,
         lema="Apagar la irritabilidad y recuperar tolerancia isométrica sin perder masa.",
         fuera=["Balón", "Golpeo", "Sprint", "Cambios de dirección", "Pliometría",
                "Copenhagen", "Sentadilla", "Zancada", "Aductores en máquina", "Braza"],
         puerta=["Dolor en reposo 0-1 durante cinco días seguidos",
                 "Tos y estornudo sin dolor",
                 "Squeeze máximo 2 o menos",
                 "Isométrico al 80 % sin reacción al día siguiente",
                 "Siete días seguidos de registro completo"]),
    dict(id="R2", nombre="Base y fuerza", desde="2026-08-31", dias=14,
         lema="Devolver fuerza real al aductor y a la cadena posterior, y reintroducir el impacto.",
         fuera=["Balón", "Sprint", "Cambios de dirección", "Golpeo", "Pliometría"],
         puerta=["Copenhagen corto 3 × 10 por lado sin reacción",
                 "Carrera continua 20 min sin reacción",
                 "Squeeze máximo 0-1",
                 "Split squat y RDL sin molestia inguinal"]),
    dict(id="R3", nombre="Construcción", desde="2026-09-14", dias=14,
         lema="Volver al impacto rápido y recuperar el balón, todavía sin velocidad máxima.",
         fuera=["Sprint máximo", "COD cerrado 135-180°", "Golpeo fuerte", "Oposición"],
         puerta=["Copenhagen largo 3 × 6-8 por lado sin reacción",
                 "Sprint al 85 % sin dolor",
                 "Cambio de dirección de 90° sin protegerte",
                 "Golpeo al 50 % sin reacción a 24 h"]),
    dict(id="R4", nombre="Específica", desde="2026-09-28", dias=14,
         lema="Velocidad, cambios de dirección cerrados y gestos de partido.",
         fuera=["Partido", "Contacto real"],
         puerta=["Checklist pre-competición completo",
                 "Sprint 95-100 % sin dolor",
                 "COD 45, 90, 135 y 180° sin protegerte",
                 "Golpeo 90-100 % sin reacción 24-48 h",
                 "Tres sesiones de campo en una semana sin empeorar"]),
    dict(id="R5", nombre="Competitiva", desde="2026-10-12", dias=14,
         lema="Entrada por minutos: 20-30, luego 45, luego 60-75, y solo después completo.",
         fuera=["Partido completo antes de cerrar el checklist"],
         puerta=["Minutos superados sin reacción al día siguiente en cada escalón"]),
]

# ── catalogo de ejercicios ───────────────────────────────────────────
# slug: (nombre, para_que, pasos, error, aviso)
from fichas_app import EJ  # noqa: E402

# ── microciclos: bloque -> dia de la semana (0=lunes) -> sesion ──────
# Cada seccion: (num, titulo, meta, tipo, items)
#   tipo "tabla": items = [ (slug|None, nombre, volumen, nota) ]
#   tipo "lista": items = [ texto ]
#   tipo "pasos": items = [ (titulo, texto) ]

MOV_BASE = [
    ("90-90-cadera", "90/90 de cadera", "2 min / lado", ""),
    ("adductor-rockback", "Adductor rockback", "2 × 10 / lado", ""),
    ("movilidad-cadera-pie", "Cadera activa de pie", "2 min", ""),
    ("brace-respiracion", "Brace con respiración 360°", "3 × 8", ""),
    ("isometrico-aductor", "Aducción isométrica", "5 × 30 s", "CLAVE"),
    ("puente-gluteo", "Puente de glúteo", "2 × 15", ""),
    ("pallof-press", "Pallof press", "2 × 10 / lado", ""),
]
MOV_CORTA = MOV_BASE[:2] + MOV_BASE[3:6]
MOV_LARGA = MOV_BASE + [
    ("dead-bug", "Dead bug lento", "3 × 8 / lado", ""),
    (None, "Plancha lateral corta", "3 × 25 s / lado", ""),
]

PLAN_A = [
    ("press-pecho-maquina", "Press de pecho en máquina", "3 × 10", ""),
    ("press-inclinado-mancuernas", "Press inclinado con mancuernas", "3 × 10", ""),
    ("press-militar-maquina", "Press militar en máquina", "3 × 10", ""),
    ("elevaciones-laterales", "Elevaciones laterales", "3 × 12-15", ""),
    ("triceps-polea", "Extensión de tríceps en polea", "3 × 12-15", ""),
    ("curl-femoral", "Curl femoral en máquina", "3 × 12", ""),
    ("extension-cuadriceps", "Extensión de cuádriceps", "3 × 12", ""),
]
PLAN_B = [
    ("jalon-al-pecho", "Jalón al pecho agarre amplio", "3 × 10", ""),
    ("remo-maquina-neutro", "Remo en máquina agarre neutro", "3 × 10", ""),
    ("remo-mancuerna", "Remo con mancuerna a una mano", "3 × 10", ""),
    ("face-pull", "Face pull en polea", "3 × 12-15", ""),
    ("curl-biceps-inclinado", "Curl de bíceps en banco inclinado", "3 × 10", ""),
    ("curl-martillo", "Curl martillo alterno", "3 × 12", ""),
    ("gemelo-de-pie", "Gemelo de pie", "3 × 15", ""),
]
PLAN_D = [
    ("press-militar-maquina", "Press militar en máquina", "3 × 12", ""),
    ("elevaciones-laterales", "Elevaciones laterales", "3 × 15", ""),
    ("face-pull", "Face pull alto", "3 × 15", ""),
    ("triceps-polea", "Extensión de tríceps en polea", "3 × 15", ""),
    ("curl-martillo", "Curl martillo alterno", "3 × 12", ""),
    ("gemelo-de-pie", "Gemelo de pie", "3 × 15", ""),
]
PLAN_C = [
    (None, "Prensa 45° pies altos", "3 × 12", ""),
    (None, "Peso muerto rumano con mancuernas", "3 × 10", ""),
    (None, "Split squat corto", "3 × 8 / lado", ""),
    ("curl-femoral", "Curl femoral en máquina", "3 × 12", ""),
    (None, "Hip thrust", "3 × 12", ""),
    ("gemelo-de-pie", "Gemelo de pie", "3 × 15", ""),
    ("pallof-press", "Pallof press", "3 × 12 / lado", ""),
]

PISCINA_25 = ["5 min nado espalda suave.",
              "10 min aqua running lento en agua profunda. Deberías poder hablar.",
              "5 min marching alto en agua a la cadera.",
              "5 min flotación pasiva y respiración."]
PISCINA_35 = ["5 min nado espalda de calentamiento.",
              "15 min agua profunda: aqua running y rodillas al pecho.",
              "10 min agua media: marching y aducciones suaves con flotador.",
              "5 min flotación pasiva."]
PISCINA_40 = ["5 min nado espalda.",
              "15 min agua profunda: aqua running, cross country, tijeras.",
              "15 min agua media: marching, aducciones, sentadilla acuática.",
              "5 min nado espalda de vuelta a la calma."]
PISTOLA = ["Dorsal y trapecio inferior, que es lo que acabas de trabajar.",
           "Cuádriceps, barrido lento de rodilla hacia arriba.",
           "Isquiosurales, de rodilla a glúteo.",
           "Glúteo mayor y medio, puntos densos sin clavar.",
           "Aductor solo en la mitad del muslo. Nunca los últimos 3-4 cm hacia el pubis."]
EMS_REC = ["Recuperación activa 3-9 Hz sobre aductores y glúteos, 20 min.",
           "Intensidad: contracción visible, sin dolor.",
           "Electrodos nunca sobre pubis, ingle ni genitales."]
CIERRE = ["Movilidad suave de cadera, 5 min.",
          "Máquina de masaje de espalda, 5-10 min en dorsal y lumbar.",
          "Shiatsu de pies si apetece."]

FISIO_VAL = [("Valoración, no solo masaje",
              "Palpación de inserción y sínfisis, test de squeeze, descarte de hernia y su criterio sobre imagen."),
             ("Manual en cadena posterior", "Glúteo medio y TFL. Descargan el aductor sin irritarlo."),
             ("Su criterio de carga", "¿Ve bien los isométricos? ¿Cuándo metería Copenhagen corto?")]
FISIO_LOC = [("Zona local, con presión suave",
              "Aductor y abdominal bajo. Máximo dos veces por semana."),
             ("Cadena posterior", "Glúteo medio, TFL, cuadrado lumbar, psoas."),
             ("Registrar la reacción", "Si mañana duele más que hoy, la dosis fue excesiva.")]
FISIO_DES = [("Descarga general post-gimnasio", "Cadena posterior y lo que hayas trabajado."),
             ("Sin zona local hoy", "Se reserva para el día de rehab larga.")]


def sesion(titulo, regla, secciones):
    return dict(titulo=titulo, regla=regla, secciones=secciones)


def sec(n, titulo, meta, tipo, items):
    return dict(n=n, titulo=titulo, meta=meta, tipo=tipo, items=items)


MICRO = {}

MICRO["R1"] = {
 0: sesion("Superior empuje + agua",
           "Vuelves de parón: RIR 3 y cargas al 60-70 %. La calidad manda sobre el peso.",
           [sec("02", "Movilidad y activación", "20 min", "tabla", MOV_BASE),
            sec("03", "Gimnasio · Plan A empuje", "40 min · RIR 3", "tabla", PLAN_A),
            sec("04", "Piscina", "25 min", "lista", PISCINA_25),
            sec("05", "Fisioterapia", "sesión de hoy", "pasos", FISIO_VAL),
            sec("06", "Electroestimulación", "20 min · tarde", "lista", EMS_REC)]),
 1: sesion("Tirón + descarga con pistola",
           "El número de esta mañana comparado con el de ayer vale más que cualquier serie.",
           [sec("02", "Movilidad y activación", "18 min", "tabla", MOV_BASE + [("dead-bug", "Dead bug lento", "2 × 8 / lado", "")]),
            sec("03", "Gimnasio · Plan B tirón", "40 min · RIR 3", "tabla", PLAN_B),
            sec("04", "Pistola de masaje", "10 min · post-gym", "lista", PISTOLA),
            sec("06", "Cierre del día", "10 min", "lista", CIERRE)]),
 2: sesion("Rehab larga + agua + fisio local",
           "El día grande de la semana. Todo el trabajo específico se concentra hoy.",
           [sec("02", "Rehab de aductor y core", "40 min", "tabla", MOV_LARGA),
            sec("04", "Piscina", "35 min", "lista", PISCINA_35),
            sec("05", "Fisioterapia · zona local", "una de las dos de la semana", "pasos", FISIO_LOC),
            sec("06", "EMS y shiatsu", "30 min · tarde", "lista", EMS_REC + ["Shiatsu lumbar y dorsal 15 min."])]),
 3: sesion("Upper extra",
           "Día de menos carga sobre la zona. Aprovecha para acumular volumen arriba.",
           [sec("02", "Movilidad y activación", "15 min", "tabla", MOV_CORTA),
            sec("03", "Gimnasio · Plan D upper extra", "40 min · RIR 2-3", "tabla", PLAN_D),
            sec("04", "Pistola de masaje", "8 min", "lista", PISTOLA)]),
 4: sesion("Gimnasio alterno + agua",
           "Alterna empuje o tirón según lo que tocara menos esta semana.",
           [sec("02", "Movilidad y activación", "18 min", "tabla", MOV_BASE),
            sec("03", "Gimnasio · Plan A o B", "40 min · RIR 3", "tabla", PLAN_A),
            sec("04", "Piscina", "25 min", "lista", PISCINA_25),
            sec("05", "Fisioterapia · descarga", "post-gimnasio", "pasos", FISIO_DES),
            sec("06", "Electroestimulación", "20 min", "lista", EMS_REC)]),
 5: sesion("Agua larga",
           "Sesión larga de agua. Es la que más volumen te da sin peaje ninguno.",
           [sec("02", "Movilidad y activación", "20 min", "tabla", MOV_BASE),
            sec("04", "Piscina", "40 min", "lista", PISCINA_40),
            sec("06", "Shiatsu completo", "30 min · noche", "lista",
                ["Cervical, dorsal y lumbar, 30 min.", "Shiatsu de pies.", "Hidratar después."])]),
 6: sesion("Descanso y test semanal",
           "Descanso real. Hoy se rellena el test y se decide si la semana que viene sube, mantiene o baja.",
           [sec("02", "Movilidad suave", "15 min", "tabla", MOV_CORTA),
            sec("09", "Test semanal", "rellenar", "test", [])]),
}

MICRO["R2"] = {
 0: sesion("Pierna completa",
           "Vuelve la pierna al gimnasio. Técnica antes que peso y rango completo.",
           [sec("02", "Movilidad y activación", "18 min", "tabla", MOV_BASE),
            sec("03", "Gimnasio · Plan C pierna", "45 min · RIR 2", "tabla", PLAN_C),
            sec("06", "Electroestimulación", "20 min", "lista", EMS_REC)]),
 1: sesion("Empuje + carrera lineal",
           "Primera carrera del reinicio. Progresiva y en el parque, sin cambios de ritmo.",
           [sec("02", "Movilidad y activación", "18 min", "tabla", MOV_BASE),
            sec("03", "Gimnasio · Plan A empuje", "40 min · RIR 2", "tabla", PLAN_A),
            sec("07", "Carrera lineal", "parque", "lista",
                ["Calentamiento 8 min de trote muy suave.",
                 "8 × 60 m al 60 %, andando la vuelta.",
                 "Vuelta a la calma 5 min y movilidad."])]),
 2: sesion("Copenhagen corto + core + agua",
           "Entra el Copenhagen. Empieza corto y solo sube si el día siguiente sale limpio.",
           [sec("02", "Rehab de aductor y core", "35 min", "tabla",
                MOV_BASE + [(None, "Copenhagen corto", "2 × 6 / lado", "NUEVO"),
                            (None, "Aductor con banda", "3 × 12 / lado", "")]),
            sec("04", "Piscina", "25 min", "lista", PISCINA_25),
            sec("05", "Fisioterapia · zona local", "una de las dos de la semana", "pasos", FISIO_LOC)]),
 3: sesion("Tirón + carrera continua",
           "Carrera continua suave, sin progresivos. Zona cómoda todo el rato.",
           [sec("02", "Movilidad y activación", "15 min", "tabla", MOV_CORTA),
            sec("03", "Gimnasio · Plan B tirón", "40 min · RIR 2", "tabla", PLAN_B),
            sec("07", "Carrera continua", "parque", "lista",
                ["12-20 min a ritmo cómodo, hablando sin ahogarte.",
                 "Terreno liso. Nada de cuestas ni cambios de ritmo."])]),
 4: sesion("Pierna ligera + Copenhagen + agua",
           "Segunda dosis de Copenhagen de la semana, con la pierna en volumen bajo.",
           [sec("02", "Rehab de aductor y core", "30 min", "tabla",
                MOV_BASE + [(None, "Copenhagen corto", "2 × 8 / lado", "")]),
            sec("03", "Gimnasio · Plan C ligero", "30 min · RIR 3", "tabla", PLAN_C[:4]),
            sec("04", "Piscina", "25 min", "lista", PISCINA_25)]),
 5: sesion("Carrera + movilidad larga",
           "Día de campo suave. Solo carrera lineal, nada de girar ni acelerar.",
           [sec("02", "Movilidad y activación", "20 min", "tabla", MOV_BASE),
            sec("07", "Carrera continua", "parque", "lista",
                ["15-25 min a ritmo cómodo.", "Movilidad larga de cadera al terminar."]),
            sec("06", "Shiatsu y pistola", "20 min", "lista", PISTOLA)]),
 6: sesion("Descanso y test semanal",
           "Descanso real y test. Si la puerta del bloque está cerca, hoy se comprueban los criterios.",
           [sec("02", "Movilidad suave", "15 min", "tabla", MOV_CORTA),
            sec("09", "Test semanal", "rellenar", "test", [])]),
}

MICRO["R3"] = {
 0: sesion("Fuerza pesada + Copenhagen largo",
           "Sube la palanca del aductor. Es el ejercicio que prepara sprint, giro y chut.",
           [sec("02", "Movilidad y activación", "18 min", "tabla", MOV_BASE),
            sec("03", "Gimnasio · Plan C pierna", "45 min · RIR 2", "tabla", PLAN_C),
            sec("08", "Aductor específico", "15 min", "tabla",
                [(None, "Copenhagen largo", "3 × 6 / lado", "NUEVO"),
                 (None, "Aductor excéntrico con banda", "3 × 8 / lado", "")])]),
 1: sesion("Balón técnico + carrera tempo",
           "Vuelve el balón, y vuelve solo como técnica. Nada de golpeo fuerte todavía.",
           [sec("02", "Movilidad y activación", "15 min", "tabla", MOV_CORTA),
            sec("07", "Campo · técnica", "35 min", "lista",
                ["Carrera tempo 15-20 min a ritmo moderado.",
                 "Pases contra pared y controles orientados con las dos piernas, 10 min.",
                 "Conducción amplia entre conos, sin cambios bruscos.",
                 "Golpeo máximo hoy: 40 %."])]),
 2: sesion("Aductor y core + movilidad",
           "Día de mantenimiento específico entre los dos días de campo.",
           [sec("02", "Rehab de aductor y core", "35 min", "tabla",
                MOV_LARGA + [(None, "Copenhagen largo", "3 × 6 / lado", "")]),
            sec("04", "Piscina", "25 min", "lista", PISCINA_25),
            sec("05", "Fisioterapia · zona local", "una de las dos de la semana", "pasos", FISIO_LOC)]),
 3: sesion("Aceleraciones y frenadas",
           "Primera velocidad del reinicio. Progresiva, con frenada en tres o cuatro pasos.",
           [sec("02", "Movilidad y activación", "18 min", "tabla", MOV_BASE),
            sec("07", "Campo · aceleración", "35 min", "lista",
                ["Calentamiento 10 min con movilidad activa.",
                 "6-8 × 10 m al 70-80 %, andando la vuelta.",
                 "4-6 × 20 m al 75-85 %.",
                 "6 frenadas progresivas desde 15 m, frenando en 3-4 pasos.",
                 "Cambios de dirección de 45°, suaves."])]),
 4: sesion("Fuerza ligera + balón",
           "Día puente. Menos volumen y buena calidad para llegar fresco al sábado.",
           [sec("02", "Movilidad y activación", "15 min", "tabla", MOV_CORTA),
            sec("03", "Gimnasio · Plan B tirón", "35 min · RIR 3", "tabla", PLAN_B),
            sec("07", "Campo · técnica", "25 min", "lista",
                ["Técnica individual y conducción.",
                 "Golpeo progresivo hasta el 50 %, 12-15 golpeos.",
                 "Cortar si el dolor pasa de 2."])]),
 5: sesion("Campo: COD y conducción",
           "Cambios de dirección de 45 a 90 grados, con balón y sin oposición.",
           [sec("02", "Movilidad y activación", "18 min", "tabla", MOV_BASE),
            sec("07", "Campo · agilidad", "40 min", "lista",
                ["Calentamiento completo 12 min.",
                 "Cambios de dirección de 45° y luego 90°, 8 repeticiones por lado.",
                 "Conducción con cambios de ritmo suaves, 10 min.",
                 "Sin duelo, sin oposición, sin sprint máximo."])]),
 6: sesion("Descanso y test semanal",
           "Descanso real y test semanal.",
           [sec("02", "Movilidad suave", "15 min", "tabla", MOV_CORTA),
            sec("09", "Test semanal", "rellenar", "test", [])]),
}

MICRO["R4"] = {
 0: sesion("Fuerza + aceleración corta",
           "Fuerza de mantenimiento con calidad, y aceleración corta al final.",
           [sec("02", "Movilidad y activación", "18 min", "tabla", MOV_BASE),
            sec("03", "Gimnasio · Plan C pierna", "40 min · RIR 2", "tabla", PLAN_C),
            sec("07", "Campo · aceleración", "20 min", "lista",
                ["6-8 × 10-20 m al 85-90 %.", "Andando la vuelta, sin prisa."])]),
 1: sesion("Balón + carrera tempo",
           "Volumen de balón con carrera moderada. Golpeo hasta el 70 %.",
           [sec("02", "Movilidad y activación", "15 min", "tabla", MOV_CORTA),
            sec("07", "Campo · técnica", "40 min", "lista",
                ["Carrera tempo 20-25 min.",
                 "Técnica, conducción rápida y pases largos progresivos.",
                 "Golpeo hasta el 70 %.",
                 "Cambios de dirección de 90° con balón."])]),
 2: sesion("Aductor y core",
           "Mantenimiento del trabajo específico, que no se abandona aunque vuelva el campo.",
           [sec("02", "Rehab de aductor y core", "30 min", "tabla",
                MOV_LARGA + [(None, "Copenhagen largo", "3 × 8 / lado", "")]),
            sec("04", "Piscina", "25 min", "lista", PISCINA_25),
            sec("05", "Fisioterapia", "descarga", "pasos", FISIO_DES)]),
 3: sesion("Sprint y COD cerrado",
           "El día más exigente del bloque. Una novedad por semana: o subes ángulo o subes velocidad, no las dos.",
           [sec("02", "Movilidad y activación", "20 min", "tabla", MOV_BASE),
            sec("07", "Campo · velocidad", "40 min", "lista",
                ["Calentamiento completo 15 min.",
                 "Aceleraciones 10-30 m al 90-95 %.",
                 "Progresivos de 40-60 m.",
                 "Cambios de dirección de 90° y 135°, y 180° solo si van bien.",
                 "Pliometría reactiva baja, 3 × 8."])]),
 4: sesion("Fuerza ligera + golpeo",
           "Golpeo progresivo hasta el 90 %, con la pierna descargada.",
           [sec("02", "Movilidad y activación", "15 min", "tabla", MOV_CORTA),
            sec("03", "Gimnasio · Plan D upper extra", "30 min", "tabla", PLAN_D),
            sec("07", "Campo · golpeo", "25 min", "lista",
                ["12-15 golpeos progresivos: 60, 70, 80 y 90 %.",
                 "Cortar si el dolor pasa de 2.",
                 "Registrar la sensación del golpeo fuerte."])]),
 5: sesion("Fútbol específico",
           "Rondos, posesión y finalización. Simular partido sin la exigencia del partido.",
           [sec("02", "Movilidad y activación", "18 min", "tabla", MOV_BASE),
            sec("07", "Campo · fútbol", "50 min", "lista",
                ["Rondos y posesión en espacio reducido.",
                 "Conducción rápida y reacción.",
                 "Finalización al 70-90 %.",
                 "Sin contacto real todavía."])]),
 6: sesion("Descanso y test semanal",
           "Descanso real, test semanal y checklist pre-competición si toca puerta.",
           [sec("02", "Movilidad suave", "15 min", "tabla", MOV_CORTA),
            sec("09", "Test semanal", "rellenar", "test", [])]),
}

MICRO["R5"] = {
 0: sesion("Fuerza de mantenimiento",
           "Mantener lo ganado con volumen bajo. La prioridad ahora es llegar fresco al fin de semana.",
           [sec("02", "Movilidad y activación", "18 min", "tabla", MOV_BASE),
            sec("03", "Gimnasio · mantenimiento", "35 min · RIR 3", "tabla", PLAN_C[:5])]),
 1: sesion("Balón + tempo",
           "Volumen moderado de balón y carrera.",
           [sec("02", "Movilidad y activación", "15 min", "tabla", MOV_CORTA),
            sec("07", "Campo", "35 min", "lista",
                ["Carrera tempo 20 min.", "Técnica y golpeo libre.", "Sin sprint máximo."])]),
 2: sesion("Aductor y core",
           "Mantenimiento específico. Copenhagen una o dos veces por semana, para siempre.",
           [sec("02", "Rehab de aductor y core", "25 min", "tabla",
                MOV_BASE + [(None, "Copenhagen largo", "3 × 8 / lado", "")]),
            sec("04", "Piscina", "20 min", "lista", PISCINA_25[:3]),
            sec("05", "Fisioterapia", "descarga", "pasos", FISIO_DES)]),
 3: sesion("Sprint de calidad",
           "Poca cantidad y mucha calidad. Series cortas al 95 % con recuperación completa.",
           [sec("02", "Movilidad y activación", "20 min", "tabla", MOV_BASE),
            sec("07", "Campo · velocidad", "30 min", "lista",
                ["Calentamiento completo 15 min.",
                 "4-6 × 40-60 m al 95 %.",
                 "Recuperación completa entre series."])]),
 4: sesion("Fuerza ligera + balón",
           "Día previo al partido. Activar sin cansar.",
           [sec("02", "Movilidad y activación", "15 min", "tabla", MOV_CORTA),
            sec("03", "Gimnasio · activación", "25 min · RIR 4", "tabla", PLAN_D[:4]),
            sec("07", "Campo", "20 min", "lista", ["Técnica suave y golpeo cómodo."])]),
 5: sesion("Partido con minutos controlados",
           "Escalón de minutos: 20-30, luego 45, luego 60-75, y solo después completo. Cada escalón exige día siguiente limpio.",
           [sec("02", "Calentamiento de partido", "20 min", "tabla", MOV_BASE),
            sec("07", "Partido", "minutos según escalón", "lista",
                ["Primer escalón: 20-30 min.",
                 "Segundo escalón: 45 min.",
                 "Tercer escalón: 60-75 min.",
                 "Partido completo solo con el checklist cerrado y sin reacción en el escalón anterior."])]),
 6: sesion("Descanso y test semanal",
           "Descanso real y test. El día siguiente al partido es el juez de todo el proceso.",
           [sec("02", "Movilidad suave", "15 min", "tabla", MOV_CORTA),
            sec("09", "Test semanal", "rellenar", "test", [])]),
}

# ── nutricion: dia de la semana -> comidas ──────────────────────────
NUTRICION = {
 0: ["Avena con leche, plátano, miel y nueces. Café.", "Yogur natural con fruta y almendras.",
     "Pollo, arroz integral y verduras salteadas.", "Leche, plátano y whey 25 g.",
     "Tostada integral con crema de cacahuete y plátano.", "Salmón al horno con patata y brócoli."],
 1: ["Tortilla de 3 claras y 1 huevo con espinacas, tostada y tomate.", "Fruta y queso fresco batido.",
     "Ternera magra con quinoa y ensalada.", "Batido de proteína con leche y plátano.",
     "Yogur natural con miel y avena.", "Merluza al vapor con arroz basmati y calabacín."],
 2: ["Yogur griego con avena, frutos rojos y miel.", "Tortita de arroz con aguacate y pavo.",
     "Lentejas estofadas con verduras y huevo cocido.", "Batido de plátano, avena y canela.",
     "Fruta y un puñado de nueces.", "Pollo con boniato asado y ensalada verde."],
 3: ["Avena nocturna con leche, chía, plátano y cacao.", "Fruta y un puñado de nueces.",
     "Salmón a la plancha con cuscús integral y espárragos.", "Yogur natural con miel y avena.",
     "Tostada integral con queso fresco.", "Tortilla francesa con champiñones y ensalada."],
 4: ["Tostadas integrales con aguacate y huevo pochado.", "Batido de proteína y una fruta.",
     "Pollo al curry con arroz integral y verduras.", "Leche, plátano y whey 25 g.",
     "Requesón con fruta y canela.", "Atún a la plancha con patata cocida y ensalada."],
 5: ["Porridge de avena con plátano, canela y nueces.", "Yogur natural con granola sin azúcar.",
     "Pasta integral con tomate natural y pavo.", "Batido de proteína.",
     "Tostada integral con queso fresco y tomate.", "Revuelto de huevos con espinacas y champiñones."],
 6: ["Huevos revueltos con tomate natural y pan integral.", "Fruta y almendras.",
     "Paella casera de pollo y verduras.", "Batido de proteína con leche y plátano.",
     "Yogur con fruta.", "Crema de calabaza con pavo y ensalada."],
}
MOMENTOS = ["Desayuno", "Media mañana", "Comida", "Post-entreno", "Merienda", "Cena"]

# Progresion del isometrico de aductor.
# R1 es el bloque que RECUPERA la tolerancia: sube de 50 a 80 en sus 14 dias.
# De R2 en adelante el trabajo pesado pasa al Copenhagen y a la fuerza, asi que
# el isometrico se queda en 80 como activacion y mantenimiento. Reiniciarlo a 50
# en cada bloque seria un retroceso.
ISO = [50, 50, 50, 60, 60, 60, 60, 70, 70, 70, 70, 80, 80, 80]
ISO_MANT = [80] * 21

for _b in BLOQUES:
    _b["iso"] = ISO if _b["id"] == "R1" else ISO_MANT
